---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-infra-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: appsets
    repoURL: https://github.com/mstefany/gitops-infra.git
    targetRevision: main
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true