---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: route.yaml
resources:
  - https://github.com/mstefany/demo-informator//deploy/manifests/openshift/?ref=main
  
  # build it on OpenShift
  - imagestream.yaml
  - buildconfig.yaml
