---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tspdata-local-developers-self-provisioner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: self-provisioner
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: tspdata-local-developers
